apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kubescape
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kubescape
  namespaceSelector:
    matchNames:
      - kubescape
  endpoints:
    - port: metrics
      interval: 30s
