global:
  imagePullPolicy: IfNotPresent

image:
  registry: quay.io
  repository: kubescape/kubescape
  tag: v1.21.0

operator:
  forceReplace: false

capabilities:
  runtimeDetection: true
  continuousScan: true

nodeAgent:
  enabled: true

prometheus:
  enabled: true
  serviceMonitor:
    enabled: true


